name: Cleanup old workflow runs

on:
  schedule:
    - cron: '0 0 1 * *' # Runs monthly at midnight UTC
  workflow_dispatch:    # Allows manual triggering from GitHub UI

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install jq

      - name: List and delete old (>28 days) workflow runs
        run: |
          gh run list --limit 200 --json databaseId,createdAt |
          jq -r '[.[] | select((now - (.createdAt | fromdateiso8601)) > (28 * 24 * 60 * 60))] | .[].databaseId' |
          tail -n +2 | xargs -I ID gh run delete ID
        env:
          GH_TOKEN: ${{ secrets. GITHUB_TOKEN }}
